AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DatabaseSize:
    Description: Choose the amount of space you want for your Deep Security Deployment!
    Type: String
    Default: 30  
  DBInstanceClass: 
    Description: Choose from a list of reccomended options for deploying the database on an RDS instance!
    Type: String
    Default: db.t2.small
  RDSMasterUsername:
    Description: Enter a master username for your PostgreSQL database!
    Type: String
    Default: MasterAdmin
  RDSMasterPassword:
    Description: Enter a secure master password for the PostgreSQL database!
    Type: String
  EnvironmentName:
    Type: String
    Description: An environment name for your demo Deep Security Environment!
    Default: DeepSec
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnetCIDR:
    Description: An IP block for your subnet where your EC2 instances will sit!
    Type: String
    Default: 10.0.1.0/24
  PrivateSubnetCIDR:
    Description: An IP block for your subnet where your RDS instance will sit!
    Type: String
    Default: 10.0.2.0/24
  VPCStackURL:
    Description: The URL of the Cloudformation Template for the VPC. 
    Type: String
    Default: https://deep-sec-haydencardwell.s3.amazonaws.com/VPC-Simple.yaml
  RDSStackURL:
    Description: The URL of the Cloudformation Template for the RDS Deployent. 
    Type: String
    Default: https://deep-sec-haydencardwell.s3.amazonaws.com/RDS.yaml
  CentOSAMI:
    Description: The AMI of the CentOS image!
    Type: String
    Default: ami-65e0e305

Resources:
  VPCStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnetCIDR: !Ref PublicSubnetCIDR
        PrivateSubnetCIDR: !Ref PrivateSubnetCIDR
      TemplateURL: !Ref VPCStackURL
      TimeoutInMinutes: 3

  

  RDSStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        DatabaseSize: !Ref DatabaseSize
        DBInstanceClass: !Ref DBInstanceClass
        RDSMasterUsername: !Ref RDSMasterUsername
        RDSMasterPassword: !Ref RDSMasterPassword
        DBSecurityGroupPara: !GetAtt VPCStack.Outputs.DBSecurityGroupId
        DBSubnetGroupName: !GetAtt VPCStack.Outputs.DBSubnetGroupName
      TemplateURL: !Ref RDSStackURL
      TimeoutInMinutes: 20
    DependsOn: VPCStack
