AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DatabaseMasterUsername:
    Description: Enter a master username for your PostgreSQL database!
    Type: String
    Default: MasterAdmin
  DatabaseMasterPassword:
    Description: Enter a secure master password for the PostgreSQL database!
    Type: String
  EnvironmentName:
    Type: String
    Description: An environment name for your demo Deep Security Environment!
    Default: DeepSec
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnetCIDR:
    Description: An IP block for your subnet where your EC2 instances will sit!
    Type: String
    Default: 10.0.1.0/24
  VPCStackURL:
    Description: The URL of the Cloudformation Template for the VPC. 
    Type: String
    Default: https://deep-sec-haydencardwell.s3.amazonaws.com/VPC-Simple.yaml
  EC2StackURL:
    Description: The URL of the Cloudformation Template for the EC2 instance and related items.
    Type: String
    Default: https://deep-sec-haydencardwell.s3.amazonaws.com/Ec2.yaml
  RedHatAMI:
    Description: The AMI of the RedHat image!
    Type: String
    Default: ami-a8d369c0
  EC2InstanceType:
    Description: The instance size of the Deep Security Manager.
    Type: String
    Default: t2.micro
  SSHKey:
    Description: The key for the Deep Security Manager
    Type: String
  UserData:
    Type: String

Resources:
  VPCStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnetCIDR: !Ref PublicSubnetCIDR
      TemplateURL: !Ref VPCStackURL
      TimeoutInMinutes: 3

  EC2Stack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        RedHatAMI: !Ref RedHatAMI
        EC2InstanceType: !Ref EC2InstanceType
        SSHKey: !Ref SSHKey
        PublicSubnet: !GetAtt VPCStack.Outputs.PublicSubnet
        UserData: !Ref UserData
        EC2SecurityGroup: !GetAtt VPCStack.Outputs.EC2SecurityGroup
      TemplateURL: !Ref EC2StackURL
      TimeoutInMinutes: 20
    DependsOn: VPCStack